Controllers/Blog/NewsViewController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.IdentityModel.Tokens;
using webtintuc.Helper;
using webtintuc.Models;
namespace webtintuc.Blog.Controllers
{
    [AllowAnonymous]
    public class NewsViewController : Controller
    {
        private readonly BlogDbContext _context;

        public NewsViewController(BlogDbContext context)
        {
            _context = context;
        }
        // [Route("/the-loai/{slugCate?}")]
        public async Task<IActionResult> Index(string slugCate, int pageSize, [FromQuery(Name = "p")] int currentPage)
        {
            var categories = _context.category.ToList(); // lay ra tat ca the loai
            CategoryModel category = null;
            if (!string.IsNullOrEmpty(slugCate))
            {
                category = await _context.category.Where(c => c.Slug == slugCate)
                                            .FirstOrDefaultAsync();
                if (category == null)
                {
                    return NotFound();
                }
            }
            ViewBag.category = category;
            var news = _context.news.Include(a => a.AuthorModel)
                                    .Include(c => c.CategoryModel)
                                    .AsQueryable();

            if (category != null)
            {
                news = news.Where(n => n.CategoryID == category.CategoryID);

            }

            //lay bai viet moi nhat
            var newsLately = _context.news.OrderByDescending(n => n.Created).FirstOrDefault();
            ViewBag.newsLately = newsLately;

            //lay bai  viet moi nhat theo the loai
            var newsLatelyByCate = _context.news.OrderByDescending(n => n.Created).Where(n => n.CategoryModel.Slug == slugCate).FirstOrDefault();
            ViewBag.newsLatelyByCate = newsLatelyByCate;

            //lay bai viet nhieu view
            var topView = _context.news.Include(a => a.AuthorModel)
                                        .Include(c => c.CategoryModel)
                                        .OrderByDescending(v => v.ViewNumber)
                                        .Take(3)
                                        .ToList();
            ViewBag.topView = topView;

            //lay bai viet nhieu view theo the loai
            var topviewByCate = _context.news
                                        .Include(a => a.AuthorModel)
                                        .Include(c => c.CategoryModel)
                                        .Where(n => n.CategoryModel.Slug == slugCate)
                                        .OrderByDescending(v => v.ViewNumber)
                                        .Take(3)
                                        .ToList();
            ViewBag.topviewByCate = topviewByCate;

            //lay cac bai cung the loai con lai
            var ortherNews = _context.news.Include(a => a.AuthorModel)
                                            .Include(c => c.CategoryModel)
                                            .Where(n => n.CategoryModel.Slug == slugCate)
                                            .ToList()
                                            .Except(topView)
                                            .Skip(1);
            //doi tac
            var partner = _context.partner.ToList();
            ViewBag.partner = partner;

            //phan trang
            var totalOtherNews = ortherNews.Count();//tong so bai viet

            if (pageSize <= 0) pageSize = 5;
            var countPage = (int)Math.Ceiling((double)totalOtherNews / pageSize);//tong so trang

            if (currentPage > countPage) currentPage = countPage;
            if (currentPage < 1) currentPage = 1;

            var pagingModel = new PagingModel()
            {
                countpages = countPage,
                currentpage = currentPage,
                generateUrl = (pageNumber) => Url.Action("Index", new
                {
                    p = pageNumber,
                    pageSize = pageSize
                })
            };

            var newsInPage = ortherNews.Skip((currentPage - 1) * pageSize)
                                    .Take(pageSize);

            ViewBag.pagingModel = pagingModel;
            ViewBag.totalOtherNews = totalOtherNews;
            ViewBag.newsInPage = newsInPage;

            return View(news.ToList());
        }

        [Route("/bai-viet/{slug}")]
        public async Task<IActionResult> Detail(string slug)
        {
            var news = _context.news.Where(n => n.Slug == slug)
                                    .Include(a => a.AuthorModel)
                                    .Include(c => c.CategoryModel)
                                    .FirstOrDefault();
            if (news == null)
            {
                return NotFound();
            }
            else
            {
                news.ViewNumber++;
                await _context.SaveChangesAsync();
            }

            //lay cac bai viet  khac cung the loai
            var ortherNews = _context.news.Where(n => n.NewsID != news.NewsID && n.CategoryID == news.CategoryID)
                                            .OrderByDescending(n => n.Created).Take(5).AsQueryable();
            ViewBag.ortherNews = ortherNews;
            return View(news);
        }
        public async Task<IActionResult> Search(string searchString)
        {
            var news = await _context.news.Include(a => a.AuthorModel)
                                    .Include(c => c.CategoryModel).ToListAsync();
            if (!string.IsNullOrEmpty(searchString))
            {

                news = news.Where(n => n.Title.ToLowerInvariant().Contains(searchString.ToLowerInvariant())).ToList();
            }
            ViewBag.ResultNumber = news.Count();
            return View(news);
        }

    }
}

Views/NewsView/Detail.cshtml
@model webtintuc.Models.NewsModel
@{
    ViewData["Title"] = Model.Title;
    IQueryable<NewsModel> ortherNews = ViewBag.ortherNews as IQueryable<NewsModel>;
}
<div class="NewsDetail">
    <h4>@Model.CategoryModel.CategoryName</h4>
    <hr>
    <h2>@Model.Title</h2>
    <div><i class="fa-regular fa-clock"></i><i>@String.Format("{0:dd/MM/yyyy}", Model.Created)</i></div>
    <div>
        @Html.Raw(Model.Content)
    </div>
    <div style="text-align: right;font-style:italic;color:rgb(128, 126, 126)">
        <i>Lượt xem: @Model.ViewNumber | </i><strong>Thực hiện: @Model.AuthorModel.AuthorName</strong>
    </div>
</div>
<div>
    <h4>Tin khác cùng chuyên mục</h4>
    <hr>
    <div>
        <ul>
            @foreach (var news in ortherNews)
            {
                <a asp-action="Detail" asp-controller="NewsView" asp-route-slug="@news.Slug">
                    <div class="media border-bottom mb-3 pb-3">
                        <img class="mr-3 w-25" src="@news.Photo">
                        <div class="media-body">
                            <h5 class="mt-0"><a style="text-decoration: none; color:black" asp-action="Detail"
                                    asp-controller="NewsView" asp-route-slug="@news.Slug">@news.Title</a>
                            </h5>
                            @news.Content.Substring(300, 400);
                        </div>
                        <div style="text-align: right;
    font-style: italic;
    color: rgb(128, 126, 126);">
                            <i> @String.Format("{0:dd/MM/yyyy}", news.Created)</i>
                        </div>
                    </div>
                </a>
            }
        </ul>
        <div>
            <p style="text-align: center;">
                <a asp-controller="NewsView" asp-action="Index" asp-route-slugCate="@Model.CategoryModel.Slug"
                    class="btn btn-primary ">Xem thêm</a>
            </p>
        </div>
    </div>
</div>
@section Sidebar {
    @await Component.InvokeAsync("TopNewsSidebar")
}

Views/NewsView/Index.cshtml
@model List<NewsModel>
@{
    List<CategoryModel> categories = ViewBag.categories as List<CategoryModel>;
    CategoryModel category = ViewBag.category as CategoryModel;
    ViewData["Title"] = category == null ? "Trang chủ" : category.CategoryName;
    var topView = ViewBag.topView;
    var newsInPage = ViewBag.newsInPage;
    var newsLately = ViewBag.newsLately;
    var topviewByCate = ViewBag.topviewByCate;
    var newsLatelyByCate = ViewBag.newsLatelyByCate;
    var partner = ViewBag.partner;
    var secondNews = Model.Skip(1).Take(3).ToList();
}
@if (ViewData["Title"] == "Trang chủ")
{

    <partial name="_StatusMessage"></partial>
    <h2>SỰ KIỆN</h2>
    <hr>
    <div>
        <a asp-action="Detail" asp-controller="NewsView" asp-route-slug="@newsLately.Slug">
            <div class="media  mb-3 pb-3">
                <img style="width:100%; height:500px" class=" h-30" src="@newsLately.Photo">
                <div class="media-body">
                    <h5 class="mt-0"><a style="text-decoration: none; color:black" asp-action="Detail"
                            asp-controller="NewsView" asp-route-slug="@newsLately.Slug">@newsLately.Title</a>
                    </h5>
                    @newsLately.Content.Substring(300, 400);
                </div>
                <div style="text-align: right; font-style: italic; color: rgb(128, 126, 126);">
                    <i> @String.Format("{0:dd/MM/yyyy}", newsLately.Created)
                    </i>|<strong>@newsLately.AuthorModel.AuthorName</strong>
                </div>
            </div>
        </a>
    </div>
    <div>
        <h2>XEM NHIỀU NHẤT</h2>
        <hr>
        <ul style="display:flex;list-style: none;">
            @foreach (var news in topView)
            {
                <li style="padding:20px">
                    <a asp-action="Detail" asp-controller="NewsView" asp-route-slug="@news.Slug">
                        <div class="media  mb-3 pb-3">
                            <img style="width:100%; height:200px" class=" h-30" src="@news.Photo">
                            <div class="media-body">
                                <strong>
                                    <h class="mt-0"><a style="text-decoration: none; color:black" asp-action="Detail"
                                            asp-controller="NewsView" asp-route-slug="@news.Slug">@news.Title</a>
                                    </h>
                                </strong>
                            </div>

                        </div>
                    </a>
                </li>
            }

        </ul>

    </div>


    <div>
        <h2>HOẠT ĐỘNG</h2>
        <hr>
        <ul style="display:flex;list-style: none;">
            @foreach (var news in secondNews)
            {
                <li style="padding:20px">
                    <a asp-action="Detail" asp-controller="NewsView" asp-route-slug="@news.Slug">
                        <div class="media  mb-3 pb-3">
                            <img style="width:100%; height:200px" class=" h-30" src="@news.Photo">
                            <div class="media-body">
                                <strong>
                                    <h class="mt-0"><a style="text-decoration: none; color:black" asp-action="Detail"
                                            asp-controller="NewsView" asp-route-slug="@news.Slug">@news.Title</a>
                                    </h>
                                </strong>
                            </div>

                        </div>
                    </a>
                </li>
            }

        </ul>

    </div>
    <div>
        <h2>ĐƠN VỊ LIÊN KẾT</h2>
        <hr>
        <ul style="display:flex;list-style: none;">
            @foreach (var news in partner)
            {
                <li style="padding:20px">
                    <div class="media  mb-3 pb-3">
                        <img style="width:100%; height:150px" class=" h-30" src="@news.Logo">
                        <div class="media-body">
                        </div>
                    </div>
                </li>
            }

        </ul>

    </div>
}
else
{
    <h2>@ViewData["Title"]</h2>
    <hr>
    <div>
        <a asp-action="Detail" asp-controller="NewsView" asp-route-slug="@newsLatelyByCate.Slug">
            <div class="media  mb-3 pb-3">
                <img style="width:100%; height:500px" class=" h-30" src="@newsLatelyByCate.Photo">
                <div class="media-body">
                    <h5 class="mt-0"><a style="text-decoration: none; color:black" asp-action="Detail"
                            asp-controller="NewsView" asp-route-slug="@newsLatelyByCate.Slug">@newsLatelyByCate.Title</a>
                    </h5>
                    @newsLatelyByCate.Content.Substring(300, 400);
                </div>
                <div style="text-align: right; font-style: italic; color: rgb(128, 126, 126);">
                    <i> @String.Format("{0:dd/MM/yyyy}", newsLatelyByCate.Created)
                    </i>|<strong>@newsLatelyByCate.AuthorModel.AuthorName</strong>
                </div>
            </div>
        </a>
    </div>
    <div>
        <ul style="display:flex;list-style: none;">
            @foreach (var news in topviewByCate)
            {
                <li style="padding:20px">
                    <a asp-action="Detail" asp-controller="NewsView" asp-route-slug="@news.Slug">
                        <div class="media  mb-3 pb-3">
                            <img style="width:100%; height:200px" class=" h-30" src="@news.Photo">
                            <div class="media-body">
                                <strong>
                                    <h class="mt-0"><a style="text-decoration: none; color:black" asp-action="Detail"
                                            asp-controller="NewsView" asp-route-slug="@news.Slug">@news.Title</a>
                                    </h>
                                </strong>
                            </div>

                        </div>
                    </a>
                </li>
            }

        </ul>

    </div>
    <div>
        <ul>
            @foreach (var news in newsInPage)
            {
                <a asp-action="Detail" asp-controller="NewsView" asp-route-slug="@news.Slug">
                    <div class="media border-bottom mb-3 pb-3">
                        <img class="mr-3 w-25" src="@news.Photo">
                        <div class="media-body">
                            <h5 class="mt-0"><a style="text-decoration: none; color:black" asp-action="Detail"
                                    asp-controller="NewsView" asp-route-slug="@news.Slug">@news.Title</a>
                            </h5>
                            @news.Content.Substring(300, 400);
                        </div>
                        <div style="text-align: right;font-style: italic;
    color: rgb(128, 126, 126);">
                            <i> @String.Format("{0:dd/MM/yyyy}", news.Created)</i>
                        </div>
                    </div>
                </a>
            }
        </ul>
        <div style="text-align: center;">
            <partial name="_Paging" model="@ViewBag.pagingModel" />
        </div>
    </div>
}

@section Sidebar {
    @await Component.InvokeAsync("TopNewsSidebar")
    @await Component.InvokeAsync("SocialSidebar")

}

Views/NewsView/Search.cshtml
@model List<NewsModel>
@{
    ViewData["Title"] = "Kết quả tìm kiếm";
    var resultNumber = ViewBag.ResultNumber;
}
@if (resultNumber <= 0)
{
    <h5 style="text-align:center;">Không tìm thấy kết quả phù hợp</h5>
    <hr>
}
<div>
    <h6 style="padding: 20px; color:rgb(73, 72, 72)">Tìm thấy @resultNumber kết quả phù hợp</h6>
    <hr>
    <ul>
        @foreach (var news in Model)
        {
            <a asp-action="Detail" asp-controller="NewsView" asp-route-slug="@news.Slug">
                <div class="media border-bottom mb-3 pb-3">
                    <img class="mr-3 w-25" src="@news.Photo">
                    <div class="media-body">
                        <h5 class="mt-0"><a style="text-decoration: none; color:black" asp-action="Detail"
                                asp-controller="NewsView" asp-route-slug="@news.Slug">@news.Title</a>
                        </h5>
                        @news.Content.Substring(300, 400);
                    </div>
                    <div style="text-align: right;font-style: italic;
    color: rgb(128, 126, 126);">
                        <i> @String.Format("{0:dd/MM/yyyy}", news.Created)</i>
                    </div>
                </div>
            </a>
        }
    </ul>
</div>
@section Sidebar {
    @await Component.InvokeAsync("TopNewsSidebar")
    @await Component.InvokeAsync("SocialSidebar")

}

Views/NewsView/_LayoutDefault.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - webtintuc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/webtintuc.styles.css" asp-append-version="true" />
</head>

<body>
    <header calss="header">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="NewsView" asp-action="Index">webtintuc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        @await Component.InvokeAsync("webtintuc.Components.CategorySidebar")

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - webtintuc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Views/NewsView/_LayoutNewsView.cshtml
@{
    Layout = "_LayoutDefault.cshtml";
}
<div class="row">
    <div class="col-md-9">
        @RenderBody()
    </div>
    <div class="col-md-3">
        @RenderSection("Sidebar")
    </div>
</div>