Controllers/AdminCPController.cs
using System.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace webtintuc.Controllers;
public class AdminCPController : Controller
{

    [Authorize(Roles = "admin")]
    // [Route("AdminControll")]
    public IActionResult Index() => View();
}

Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using webtintuc.Models;
using webtintuc.Role.Models;

namespace webtintuc.Controllers
{
    [Authorize(Roles = "admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly BlogDbContext _context;
        private readonly UserManager<AppUser> _userManager;
        public RoleController(RoleManager<IdentityRole> roleManager, BlogDbContext context, UserManager<AppUser> userManager)
        {
            _roleManager = roleManager;
            _context = context;
            _userManager = userManager;
        }

        [TempData]
        public string StatusMessage { get; set; }

        //GET: hien thi danh sach role
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var role = await _roleManager.Roles.ToListAsync();
            return View(role);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateRoleModel createRoleModel)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var newRole = new IdentityRole(createRoleModel.Name!);
            var result = await _roleManager.CreateAsync(newRole);
            if (result.Succeeded)
            {
                StatusMessage = $"Bạn vừa tạo mới role: {newRole.Name}";
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var erro in result.Errors)
                {
                    ModelState.AddModelError("", erro.Description);
                }
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null) return NotFound("Không tìm thấy role");
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound("Không tìm thấy role");
            }
            return View(role);
        }
        //POST : Xóa role
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(string id)
        {
            if (id == null) return NotFound("role không tồn tại");
            var role = await _roleManager.FindByIdAsync(id);
            var result = await _roleManager.DeleteAsync(role);
            if (result.Succeeded)
            {
                StatusMessage = $"Bạn vừa xóa {role.Name}";
                return View("Index");
            }
            else
            {
                foreach (var r in result.Errors)
                {
                    ModelState.AddModelError("", r.Description);
                }
            }
            return View(role);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(string id, [Bind("Name")] EditRoleModel editRoleModel)
        {
            if (id == null) return NotFound("Không tìm thấy role");
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound("Role không tồn tại");
            }
            editRoleModel.Name = role.Name;
            return View(editRoleModel);
        }
        [HttpPost, ActionName("Edit")]
        public async Task<IActionResult> EditConfirm(string id, [Bind("Name")] EditRoleModel editRoleModel)
        {
            if (id == null) return NotFound();
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            if (!ModelState.IsValid)
            {
                return View();
            }
            role.Name = editRoleModel.Name;
            var result = await _roleManager.UpdateAsync(role);
            if (result.Succeeded)
            {
                StatusMessage = $"Bạn vừa cập nhật role {editRoleModel.Name}";
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var err in result.Errors)
                {
                    ModelState.AddModelError("", err.Description);
                }
            }
            return View(editRoleModel);
        }
    }
}

Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using webtintuc.Models;
using webtintuc.User.Models;

namespace webtintuc.Controllers
{
    [Authorize(Roles = "admin")]
    public class UserController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly BlogDbContext _context;
        private readonly UserManager<AppUser> _userManager;
        public UserController(RoleManager<IdentityRole> roleManager, BlogDbContext context, UserManager<AppUser> userManager)
        {
            _roleManager = roleManager;
            _context = context;
            _userManager = userManager;
        }
        [TempData]
        public string StatusMessage { set; get; }
        public async Task<IActionResult> Index([FromQuery(Name = "p")] int currentPage)
        {
            var model = new UserListModel();
            model.currentPage = currentPage;

            var qr = _userManager.Users.OrderBy(u => u.UserName);

            model.totalUsers = await qr.CountAsync();
            model.countPages = (int)Math.Ceiling((double)model.totalUsers / model.ITEMS_PER_PAGE);

            if (model.currentPage < 1)
                model.currentPage = 1;
            if (model.currentPage > model.countPages)
                model.currentPage = model.countPages;

            var qr1 = qr.Skip((model.currentPage - 1) * model.ITEMS_PER_PAGE)
                        .Take(model.ITEMS_PER_PAGE)
                        .Select(u => new UserAndRole()
                        {
                            Id = u.Id,
                            UserName = u.UserName,
                        });

            model.users = await qr1.ToListAsync();

            foreach (var user in model.users)
            {
                var roles = await _userManager.GetRolesAsync(user);
                user.RoleName = string.Join(",", roles);
            }

            return View(model);
        }
        //GET gán role cho user
        [HttpGet]
        public async Task<IActionResult> AddRole(string id)
        {
            var model = new AddRoleForUserModel();
            if (id.IsNullOrEmpty())
            {
                return NotFound("Người dùng không tồn tại");
            }
            model.appUser = await _userManager.FindByIdAsync(id);
            if (model.appUser == null)
            {
                return NotFound("Người dùng không tồn tại");
            }
            model.RoleName = (await _userManager.GetRolesAsync(model.appUser)).ToArray();
            List<string> roleName = await _roleManager.Roles.Select(r => r.Name).ToListAsync();
            ViewBag.allRoles = new SelectList(roleName);
            return View(model);
        }
        //POST gán role cho user
        [HttpPost, ActionName("AddRole")]
        public async Task<IActionResult> AddRoleConfirm(string id, [Bind("RoleName")] AddRoleForUserModel model)
        {
            if (id.IsNullOrEmpty()) return NotFound();
            model.appUser = await _userManager.FindByIdAsync(id);
            if (model.appUser == null)
            {
                return NotFound("Không tìm thấy người dùng");
            }
            var oldRoleName = (await _userManager.GetRolesAsync(model.appUser)).ToArray();
            var deleteRoleName = oldRoleName.Where(r => !model.RoleName.Contains(r));
            var addRoleName = model.RoleName.Where(r => !oldRoleName.Contains(r));
            List<string> roleName = await _roleManager.Roles.Select(r => r.Name).ToListAsync();
            ViewBag.allRoles = new SelectList(roleName);
            var resultDelete = await _userManager.RemoveFromRolesAsync(model.appUser, deleteRoleName);
            if (!resultDelete.Succeeded)
            {
                foreach (var error in resultDelete.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
                return View();

            }
            var resultAdd = await _userManager.AddToRolesAsync(model.appUser, addRoleName);
            if (!resultAdd.Succeeded)
            {
                foreach (var error in resultAdd.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
                return View();

            }
            StatusMessage = $"Bạn vừa cập nhật role cho {model.appUser.UserName}";
            return RedirectToAction("Index");

        }
    }


}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<AppUser> signInManager
@inject UserManager<AppUser> userManager
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewData["Title"]</title>

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    <!-- Custom fonts for this template-->
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">

    <!-- Bootstrap core JavaScript-->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/lib/jquery-easing/jquery.easing.min.js"></script>

    @* chen javascript tinymce *@
    <script src="~/js/tinymce/js/tinymce/tinymce.min.js" referrerpolicy="origin"></script>



</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" asp-action="Index"
                asp-controller="AdminCP">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Admin ControllPlane <sup></sup></div>
            </a>
            @await RenderSectionAsync("Sidebar", false)
            <!-- Divider  đường kẻ ngang-->
            <hr class="sidebar-divider">
            <!-- Nav Item - Dashboard -->
            <!-- Heading tiêu đề -->
            <div class="sidebar-heading">
                Quản lý website
            </div>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="News" asp-action="Index">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Bài viết</span>
                </a>
            </li>

            <!-- Divider  đường kẻ ngang-->
            <hr class="sidebar-divider">

            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Category" asp-action="Index">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Danh mục</span>
                </a>
            </li>
            <!-- Divider  đường kẻ ngang-->
            <hr class="sidebar-divider">

            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Author" asp-action="Index">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Tác giả</span>
                </a>
            </li>
            <!-- Divider  đường kẻ ngang-->
            <hr class="sidebar-divider">

            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Contact" asp-action="Index">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Liên hệ</span>
                </a>
            </li>
            <hr class="sidebar-divider">
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Partner" asp-action="Index">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Đơn vị liên kết</span>
                </a>
            </li>
            @* <!-- Divider đường kẻ ngang-->
            <hr class="sidebar-divider">
            <li class="nav-item">
            <a class="nav-link" asp-area="" asp-controller="Comment" asp-action="Index">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Bình luận</span>
            </a>
            </li> *@
            <!-- Divider  đường kẻ ngang-->
            <hr class="sidebar-divider">
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="User" asp-action="Index">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Người dùng</span>
                </a>
            </li>
            <!-- Divider  đường kẻ ngang-->
            <hr class="sidebar-divider">
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Role" asp-action="Index">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Role</span>
                </a>
            </li>


            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar)  buton bật tắt sidebar -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->
                    <form
                        class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                                aria-label="Search" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="button">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                        </li>
                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <partial name="_LoginPartial.cshtml" />

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    @RenderBody()

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>ASP.NET MVC 2024</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewData["Title"]</title>

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    <!-- Custom fonts for this template-->
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">

    <!-- Bootstrap core JavaScript-->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/lib/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.min.js"></script>

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        @RenderBody()

    </div>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Views/Shared/_Paging.cshtml
@*
Model:
- currentPage:int - Trang hiện tại
- countPages:int - tổng số trang
- generateUrl:delegate Func<int?, string> trả về URL tương ứng với trang p (1,2,3 ...)
*@

@model webtintuc.Helper.PagingModel
@{
    int currentPage = Model.currentpage;
    int countPages = Model.countpages;
    var generateUrl = Model.generateUrl;



    if (currentPage > countPages)
        currentPage = countPages;

    if (countPages <= 1) return;


    int? preview = null;
    int? next = null;

    if (currentPage > 1)
        preview = currentPage - 1;

    if (currentPage < countPages)
        next = currentPage + 1;

    // Các trang hiện thị trong điều hướng
    List<int> pagesRanges = new List<int>();


    int delta = 5; // Số trang mở rộng về mỗi bên trang hiện tại
    int remain = delta * 2; // Số trang hai bên trang hiện tại

    pagesRanges.Add(currentPage);
    // Các trang phát triển về hai bên trang hiện tại
    for (int i = 1; i <= delta; i++)
    {
        if (currentPage + i <= countPages)
        {
            pagesRanges.Add(currentPage + i);
            remain--;
        }

        if (currentPage - i >= 1)
        {
            pagesRanges.Insert(0, currentPage - i);
            remain--;
        }

    }
    // Xử lý thêm vào các trang cho đủ remain
    //(xảy ra ở đầu mút của khoảng trang không đủ trang chèn vào)
    if (remain > 0)
    {
        if (pagesRanges[0] == 1)
        {
            for (int i = 1; i <= remain; i++)
            {
                if (pagesRanges.Last() + 1 <= countPages)
                {
                    pagesRanges.Add(pagesRanges.Last() + 1);
                }
            }
        }
        else
        {
            for (int i = 1; i <= remain; i++)
            {
                if (pagesRanges.First() - 1 > 1)
                {
                    pagesRanges.Insert(0, pagesRanges.First() - 1);
                }
            }
        }
    }

}

@* PHÁT SINH HTML*@

<ul class="pagination">
    <!-- Previous page link -->
    @if (preview != null)
    {
        <li class="page-item">
            <a class="page-link" href="@generateUrl(preview)">Trang trước</a>
        </li>
    }
    else
    {
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Trang trước</a>
        </li>
    }

    <!-- Numbered page links -->
    @foreach (var pageitem in pagesRanges)
    {
        if (pageitem != currentPage)
        {
            <li class="page-item">
                <a class="page-link" href="@generateUrl(pageitem)">
                    @pageitem
                </a>
            </li>
        }
        else
        {
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="#">@pageitem <span class="sr-only">(current)</span></a>
            </li>
        }
    }


    <!-- Next page link -->
    @if (next != null)
    {
        <li class="page-item">
            <a class="page-link" href="@generateUrl(next)">Trang sau</a>
        </li>
    }
    else
    {
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Trang sau</a>
        </li>
    }
</ul>

Views/Shared/_StatusMessage.cshtml
@{
    var mgs = TempData["StatusMessage"] as string;
}

@if (!String.IsNullOrEmpty(mgs))
{
    var statusMessageClass = mgs.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" he request matched multiple endpoints><span aria-hidden="true">&times;</span></button>
        @mgs
    </div>
}

Views/Shared/_none.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - webtintuc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/webtintuc.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
    </header>
    <div class="container" style="padding-top: 150px;">

        @RenderBody()

    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>